exports.avatars = [
    'Baby Chrizzy',
    'Biancer',
    'Der böse Wolf',
    'Drachenbruder',
    'Drachenlady',
    'Erdbeerchen',
    'Ey Malla',
    'Gummibeerchen',
    'Leiffels',
    'Nachber',
    'Reiner',
    'Ramoner',
    'Riter',
    'Rudi',
    'Marion',
    'Zoomulle',
];